version: "3"

vars:
  HOST:
    sh: hostname -s
  USER:
    sh: echo ${SUDO_USER:-$(whoami)}

includes:
  nix:
    taskfile: ./taskfiles/nix
    dir: .
  vm:
    taskfile: ./taskfiles/vm
    dir: .
  secrets:
    taskfile: ./taskfiles/secrets
    dir: .

tasks:
  default:
    cmd: task -l

  switch:
    desc: Apply nix config for the current host
    cmds:
      - cmd: 'sudo darwin-rebuild switch --flake ".#{{.USER}}@{{.HOST}}"'
        platforms: [darwin]
      - cmd: 'sudo nixos-rebuild switch --flake ".#{{.HOST}}"'
        platforms: [linux]
        if: "[ -f /etc/NIXOS ]"
      - cmd: 'home-manager switch --flake ".#{{.USER}}@{{.HOST}}"'
        platforms: [linux]
        if: "[ ! -f /etc/NIXOS ]"

  update:
    desc: Update all flake inputs
    cmds:
      - nix flake update

  check:
    desc: Run all Dagger checks
    cmds:
      - dagger check

  dev:
    desc: Launch an interactive dev container
    vars:
      BRANCH:
        sh: git branch --show-current
      CLONE_URL:
        sh: git remote get-url origin
    cmds:
      - >-
        sops exec-env secrets/dotfiles.yaml '
        dagger call dev dev
        --branch "{{.BRANCH}}"
        --clone-url "{{.CLONE_URL}}"
        --repo-source .
        --git-config ~/.config/git
        --tz "{{.TZ | default "America/New_York"}}"
        --colorterm "{{.COLORTERM}}"
        --kagi-api-key env://KAGI_API_KEY'
