{
  pkgs,
  config,
  lib,
  ...
}:

let
  inherit (config.lib.stylix) colors;
  inherit (config.stylix) fonts;
  colorHelpers = import ../lib/colors.nix { inherit lib; };
  accentColor = colorHelpers.rgbToHsl colors "base0E";

  themeName = "Stylix Base16";

  manifest = pkgs.writeText "manifest.json" (
    builtins.toJSON {
      name = themeName;
      version = "1.0.0";
      minAppVersion = "1.0.0";
    }
  );

  mkConfig = name: value: pkgs.writeText name (builtins.toJSON value);

  configs = {
    "appearance.json" = mkConfig "appearance.json" {
      translucency = false;
      cssTheme = themeName;
      baseFontSize = fonts.sizes.terminal;
      interfaceFontFamily = fonts.sansSerif.name;
      textFontFamily = fonts.sansSerif.name;
      monospaceFontFamily = fonts.monospace.name;
    };
    "app.json" = mkConfig "app.json" {
      showLineNumber = true;
      vimMode = false;
      livePreview = false;
      defaultViewMode = "preview";
    };
    "backlink.json" = mkConfig "backlink.json" {
      backlinkInDocument = true;
    };
    "canvas.json" = mkConfig "canvas.json" {
      snapToObjects = true;
      snapToGrid = true;
    };
    "community-plugins.json" = mkConfig "community-plugins.json" [
      "obsidian-git"
    ];
    "core-plugins.json" = mkConfig "core-plugins.json" {
      file-explorer = true;
      global-search = true;
      switcher = true;
      graph = true;
      backlink = true;
      canvas = true;
      outgoing-link = true;
      tag-pane = true;
      footnotes = true;
      properties = true;
      page-preview = true;
      daily-notes = true;
      templates = true;
      note-composer = true;
      command-palette = true;
      slash-command = true;
      editor-status = true;
      bookmarks = true;
      markdown-importer = true;
      zk-prefixer = false;
      random-note = false;
      outline = true;
      word-count = true;
      slides = true;
      audio-recorder = false;
      workspaces = false;
      file-recovery = true;
      publish = false;
      sync = true;
      bases = true;
      webviewer = false;
    };
    "daily-notes.json" = mkConfig "daily-notes.json" {
      format = "YYYY/MM/YYYY-MM-DD";
    };
    "graph.json" = mkConfig "graph.json" {
      collapse-filter = true;
      search = "";
      showTags = false;
      showAttachments = false;
      hideUnresolved = false;
      showOrphans = true;
      collapse-color-groups = true;
      colorGroups = [ ];
      collapse-display = true;
      showArrow = false;
      textFadeMultiplier = 0;
      nodeSizeMultiplier = 1;
      lineSizeMultiplier = 1;
      collapse-forces = true;
      centerStrength = 0.5;
      repelStrength = 10;
      linkStrength = 1;
      linkDistance = 250;
      scale = 1;
      close = true;
    };
  };

  pluginConfigs = {
    "obsidian-git/data.json" = mkConfig "obsidian-git-data.json" {
      commitMessage = "vault backup: {{date}}";
      autoCommitMessage = "vault backup: {{date}}";
      commitDateFormat = "YYYY-MM-DD HH:mm:ss";
      autoSaveInterval = 15;
      autoPushInterval = 0;
      autoPullInterval = 0;
      autoPullOnBoot = false;
      disablePush = true;
      pullBeforePush = false;
      disablePopups = false;
      showErrorNotices = true;
      listChangedFilesInMessageBody = false;
      showStatusBar = true;
      syncMethod = "rebase";
      mergeStrategy = "none";
      customMessageOnAutoBackup = false;
      autoBackupAfterFileChange = false;
      treeStructure = false;
      refreshSourceControl = true;
      refreshSourceControlTimer = 7000;
      differentIntervalCommitAndPush = true;
      changedFilesInStatusBar = false;
      showBranchStatusBar = true;
      showFileMenu = true;
      authorInHistoryView = "full";
      dateInHistoryView = true;
      diffStyle = "split";
      hunks = {
        showSigns = true;
        hunkCommands = false;
        statusBar = "colored";
      };
      lineAuthor = {
        show = false;
        followMovement = "inactive";
        authorDisplay = "initials";
        showCommitHash = false;
        dateTimeFormatOptions = "date";
        dateTimeFormatCustomString = "YYYY-MM-DD HH:mm";
        dateTimeTimezone = "viewer-local";
        coloringMaxAge = "1y";
        colorNew = colorHelpers.rgbToAttrs colors "base0B";
        colorOld = colorHelpers.rgbToAttrs colors "base08";
        textColorCss = "var(--text-muted)";
        ignoreWhitespace = false;
        gutterSpacingFallbackLength = 5;
      };
    };
  };

  gitignore = pkgs.writeText "obsidian-gitignore" ''
    .DS_Store
    .obsidian/
  '';

  obsidianCSS = pkgs.writeText "theme.css" ''
    /* Generated by home-manager from stylix base16 palette */
    .theme-dark {
      /* Accent (HSL derived from base0E) */
      --accent-h: ${toString accentColor.h};
      --accent-s: ${toString accentColor.s}%;
      --accent-l: ${toString accentColor.l}%;

      /* Backgrounds */
      --background-primary: #${colors.base00};
      --background-primary-alt: #${colors.base01};
      --background-secondary: #${colors.base01};
      --background-secondary-alt: #${colors.base00};
      --background-modifier-border: #${colors.base02};
      --background-modifier-form-field: #${colors.base01};
      --background-modifier-form-field-highlighted: #${colors.base02};
      --background-modifier-box-shadow: rgba(0, 0, 0, 0.3);
      --background-modifier-success: #${colors.base0B};
      --background-modifier-error: #${colors.base08};
      --background-modifier-error-hover: #${colors.base08};
      --background-modifier-cover: rgba(0, 0, 0, 0.6);

      /* Text */
      --text-normal: #${colors.base06};
      --text-muted: #${colors.base05};
      --text-faint: #${colors.base04};
      --text-on-accent: #${colors.base00};
      --text-on-accent-inverted: #${colors.base06};
      --text-error: #${colors.base08};
      --text-success: #${colors.base0B};
      --text-accent: #${colors.base0E};
      --text-accent-hover: #${colors.base0D};
      --bold-color: #${colors.base0A};

      /* Interactive */
      --interactive-normal: #${colors.base01};
      --interactive-hover: #${colors.base02};
      --interactive-accent: #${colors.base0E};
      --interactive-accent-hover: #${colors.base0D};

      /* Panel/navigation */
      --panel-border-color: #${colors.base01};
      --nav-item-color-active: #${colors.base00};
      --divider-color-hover: #${colors.base02};

      /* Scrollbar */
      --scrollbar-bg: #${colors.base00};
      --scrollbar-thumb-bg: #${colors.base02};
      --scrollbar-active-thumb-bg: #${colors.base03};

      /* Named colors (used by syntax highlighting rules) */
      --red: #${colors.base08};
      --orange: #${colors.base09};
      --yellow: #${colors.base0A};
      --green: #${colors.base0B};
      --aqua: #${colors.base0C};
      --blue: #${colors.base0D};
      --purple: #${colors.base0E};
      --gray-1: #${colors.base03};
      --gray-2: #${colors.base05};

      /* Syntax highlighting */
      --code-normal: #${colors.base05};
      --code-comment: #${colors.base03};
      --code-function: #${colors.base0D};
      --code-important: #${colors.base09};
      --code-keyword: #${colors.base0E};
      --code-operator: #${colors.base05};
      --code-property: #${colors.base08};
      --code-punctuation: #${colors.base05};
      --code-string: #${colors.base0B};
      --code-tag: #${colors.base08};
      --code-value: #${colors.base09};

      /* UI components */
      --ribbon-background: var(--background-primary);
      --drag-ghost-background: var(--background-secondary-alt);
      --background-modifier-message: var(--background-secondary-alt);
      --tab-outline-color: transparent;
      --divider-color: transparent;
      --prompt-border-color: var(--panel-border-color);
      --modal-border-color: var(--panel-border-color);
      --background-modifier-border-hover: var(--interactive-hover);
      --background-modifier-border-focus: var(--interactive-hover);
      --checkbox-color: var(--text-accent);
      --checkbox-color-hover: var(--text-accent-hover);
      --nav-item-background-active: var(--interactive-accent);
      --tag-color: var(--yellow);
      --tag-background: var(--background-primary-alt);
      --tag-color-hover: var(--yellow);
      --tag-background-hover: var(--background-primary-alt);
      --tag-padding-x: 4px;
      --tag-padding-y: 2px;
      --tag-radius: 4px;
      --inline-title-weight: var(--bold-weight);
      --link-decoration: none;
      --link-external-decoration: none;
      --embed-padding: 0 0 0 var(--size-4-4);

      /* Fonts */
      --font-text-override: "${fonts.sansSerif.name}", sans-serif;
      --font-monospace-override: "${fonts.monospace.name}", monospace;
      --font-interface-override: "${fonts.sansSerif.name}", sans-serif;
    }

    /* Token-based syntax highlighting (Prism.js + CodeMirror) */
    .token.comment, .token.prolog, .token.doctype, .token.cdata,
    .HyperMD-codeblock .cm-comment { color: var(--gray-1) !important; }

    .token.punctuation,
    .HyperMD-codeblock .cm-hmd-codeblock, .HyperMD-codeblock .cm-bracket { color: var(--gray-2) !important; }

    .token.selector, .token.tag,
    .HyperMD-codeblock .cm-tag, .HyperMD-codeblock .cm-property, .HyperMD-codeblock .cm-meta,
    .HyperMD-codeblock .cm-qualifier, .HyperMD-codeblock .cm-header, .HyperMD-codeblock .cm-quote,
    .HyperMD-codeblock .cm-hr, .HyperMD-codeblock .cm-link { color: var(--red) !important; }

    .token.property, .token.boolean, .token.number, .token.constant, .token.symbol,
    .token.attr-name, .token.deleted,
    .HyperMD-codeblock .cm-number, .HyperMD-codeblock .cm-atom,
    .HyperMD-codeblock .cm-attribute { color: var(--orange) !important; }

    .token.string, .token.char, .token.attr-value, .token.builtin, .token.inserted,
    .HyperMD-codeblock .cm-string, .HyperMD-codeblock .cm-builtin { color: var(--green) !important; }

    .token.operator, .token.entity, .token.url, .language-css .token.string,
    .style .token.string,
    .HyperMD-codeblock .cm-string-2, .HyperMD-codeblock .cm-operator { color: var(--aqua) !important; }

    .token.atrule, .token.keyword,
    .HyperMD-codeblock .cm-keyword { color: var(--purple) !important; }

    .token.function, .token.macro.property,
    .HyperMD-codeblock .cm-def, .HyperMD-codeblock .cm-variable { color: var(--blue) !important; }

    .token.class-name,
    .HyperMD-codeblock .cm-variable-2, .HyperMD-codeblock .cm-variable-3 { color: var(--yellow) !important; }

    .token.regex, .token.important, .token.variable { color: var(--purple) !important; }

    .token.important, .token.bold { font-weight: bold !important; }
    .token.italic { font-style: italic !important; }
    .token.entity { cursor: help !important; }

    code[class*='language-'], pre[class*='language-'] {
      text-align: left !important;
      white-space: pre !important;
      word-spacing: normal !important;
      word-break: normal !important;
      word-wrap: normal !important;
      line-height: 1.5 !important;
      tab-size: 4 !important;
      hyphens: none !important;
    }
  '';
in
{
  home.packages = with pkgs; [
    obsidian
  ];

  home.activation.obsidianStylix = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    vaults_dir="$HOME/Documents/vaults"
    if [ -d "$vaults_dir" ]; then
      for obsidian_dir in "$vaults_dir"/*/.obsidian; do
        if [ -d "$obsidian_dir" ]; then
          theme_dir="$obsidian_dir/themes/${themeName}"
          mkdir -p "$theme_dir"
          cp -f "${manifest}" "$theme_dir/manifest.json"
          cp -f "${obsidianCSS}" "$theme_dir/theme.css"
          ${lib.concatStringsSep "\n          " (
            lib.mapAttrsToList (name: path: ''cp -f "${path}" "$obsidian_dir/${name}"'') configs
          )}
          ${lib.concatStringsSep "\n          " (
            lib.mapAttrsToList (name: path: ''
              mkdir -p "$obsidian_dir/plugins/$(dirname "${name}")"
              cp -f "${path}" "$obsidian_dir/plugins/${name}"
            '') pluginConfigs
          )}

          vault_dir="$(dirname "$obsidian_dir")"
          cp -f "${gitignore}" "$vault_dir/.gitignore"
          if [ ! -d "$vault_dir/.git" ]; then
            ${pkgs.git}/bin/git init "$vault_dir"
          fi
        fi
      done
    fi
  '';
}
