k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/k9s-screen-dumps
  refreshRate: 1
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    reactive: true
    noIcons: false
    defaultsToFullScreen: false
    skin: one-dark
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: nicolaka/netshoot:b2f26ec9a306e27037573443b63f00e2e94a82dd
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 1000
    buffer: 10000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
