version: "3"

tasks:
  default:
    cmd: task -g -l

  ssh:upload-key:
    desc: Upload local SSH public key to GitHub
    vars:
      HOST:
        sh: hostname -s
      KEY_FILE: '{{.KEY_FILE | default "~/.ssh/id_ed25519.pub"}}'
      KEY_TITLE: '{{.KEY_TITLE | default "{{.HOST}}"}}'
    cmds:
      - gh ssh-key add {{.KEY_FILE}} --title "{{.KEY_TITLE}}"

  displays:
    desc: Configure displays
    cmds:
      - displayplacer "id:s4294967295 res:2560x1440 hz:144 color_depth:7 enabled:true scaling:off origin:(0,0) degree:0"
      - displayplacer "id:s1686152384 res:2560x1440 hz:144 color_depth:8 enabled:true scaling:off origin:(-2560,0) degree:0"
