# Body of nixos-lima's `services.lima.enable` lima-init systemd
# service, with mount handling rewritten to emit systemd .mount units
# under /run instead of appending to /etc/fstab. See lima-hardware.nix
# for the rationale; tldr: NixOS regenerates /etc/fstab on activation,
# so the upstream imperative-fstab approach loses every Lima virtiofs
# mount on the next switch, and its awk-to-fstab also mangled mount
# points containing whitespace.
#
# Placeholders substituted by lima-hardware.nix via lib.replaceStrings:
#   @CIDATA_MNT@  -> /mnt/lima-cidata
#   @LIMA_PATH@   -> nix-store binpath for shadow/gawk/systemd/mount

echo "attempting to fetch configuration from LIMA user data..."

if [ -f @CIDATA_MNT@/lima.env ]; then
  echo "storage exists"
else
  echo "storage not exists"
  exit 2
fi
# ripped from https://github.com/lima-vm/alpine-lima/blob/main/lima-init.sh
# We can't just source lima.env because values might have spaces in them
while read -r line; do export "$line"; done <"@CIDATA_MNT@"/lima.env

export PATH=@LIMA_PATH@:$PATH

# Create user
id -u "$LIMA_CIDATA_USER" >/dev/null 2>&1 || useradd --home-dir "$LIMA_CIDATA_HOME" --create-home --uid "$LIMA_CIDATA_UID" "$LIMA_CIDATA_USER"

# Add user to sudoers
usermod -a -G wheel $LIMA_CIDATA_USER
usermod -a -G users $LIMA_CIDATA_USER

echo "fix symlink for /bin/bash"
ln -fs /run/current-system/sw/bin/bash /bin/bash

# Create authorized_keys
LIMA_CIDATA_SSHDIR="$LIMA_CIDATA_HOME"/.ssh
mkdir -p -m 700 "$LIMA_CIDATA_SSHDIR"
awk '
match($0, /^([[:space:]]*)ssh-authorized-keys:/, m) { ident="^" m[1] "[[:space:]]+-[[:space:]]+"; flag=1; next }
flag && $0 !~ ident { flag=0; next }
flag && $0 ~ ident { sub(ident, ""); gsub("\"", ""); print $0 }
' "@CIDATA_MNT@"/user-data >"$LIMA_CIDATA_SSHDIR"/authorized_keys
LIMA_CIDATA_GID=$(id -g "$LIMA_CIDATA_USER")
chown -R "$LIMA_CIDATA_UID:$LIMA_CIDATA_GID" "$LIMA_CIDATA_SSHDIR"
chmod 600 "$LIMA_CIDATA_SSHDIR"/authorized_keys

LIMA_SSH_KEYS_CONF=/etc/ssh/authorized_keys.d
mkdir -p -m 700 "$LIMA_SSH_KEYS_CONF"
cp "$LIMA_CIDATA_SSHDIR"/authorized_keys "$LIMA_SSH_KEYS_CONF/$LIMA_CIDATA_USER"

# Emit Lima virtiofs mounts as systemd .mount units under /run.
echo "Writing Lima mount units to /run/systemd/system"
mkdir -p /run/systemd/system

WANTED_UNITS=""
while IFS=$'\t' read -r src mp fstype opts; do
  [ -z "$src" ] && continue
  unit_name=$(systemd-escape --suffix=mount --path "$mp")
  unit_path="/run/systemd/system/$unit_name"
  mkdir -p "$mp"
  {
    printf '# Generated by lima-init. Do not edit.\n'
    printf '[Unit]\n'
    printf 'Description=Lima virtiofs mount %s\n' "$mp"
    printf 'DefaultDependencies=no\n'
    printf 'After=local-fs-pre.target\n'
    printf 'Before=local-fs.target\n'
    printf '\n'
    printf '[Mount]\n'
    printf 'What=%s\n' "$src"
    printf 'Where=%s\n' "$mp"
    printf 'Type=%s\n' "$fstype"
    printf 'Options=%s\n' "$opts"
  } >"$unit_path"
  WANTED_UNITS="$WANTED_UNITS $unit_name"
done < <(
  awk -f- "@CIDATA_MNT@"/user-data <<'EOF'
/^mounts:/ {
    flag = 1
    next
}
/^[^:[:space:]][^:]*:/ {
    flag = 0
}
/^ *$/ {
    flag = 0
}
flag {
    sub(/^[[:space:]]*- \[/, "")
    sub(/\][[:space:]]*$/, "")
    n = split($0, fields, /"?, "?/)
    if (n < 4) next
    for (i = 1; i <= n; i++) gsub(/^"|"$/, "", fields[i])
    printf "%s\t%s\t%s\t%s\n", fields[1], fields[2], fields[3], fields[4]
}
EOF
)

systemctl daemon-reload
for u in $WANTED_UNITS; do
  systemctl start "$u" || echo "Failed to start $u"
done

# Run system provisioning scripts
echo "Running system provisioning scripts"
if [ -d "@CIDATA_MNT@"/provision.system ]; then
  for f in "@CIDATA_MNT@"/provision.system/*; do
    echo "Executing $f"
    if ! "$f"; then
      echo "Failed to execute $f"
    fi
  done
fi

# Run user provisioning scripts
echo "Running user provisioning scripts"
USER_SCRIPT="$LIMA_CIDATA_HOME/.lima-user-script"
if [ -d "@CIDATA_MNT@"/provision.user ]; then
  if [ ! -f /sbin/openrc-run ]; then
    until [ -e "/run/user/$LIMA_CIDATA_UID/systemd/private" ]; do sleep 3; done
  fi
  params=$(grep -o '^PARAM_[^=]*' "@CIDATA_MNT@"/param.env | paste -sd ,)
  for f in "@CIDATA_MNT@"/provision.user/*; do
    echo "Executing $f (as user $LIMA_CIDATA_USER)"
    cp "$f" "$USER_SCRIPT"
    chown "$LIMA_CIDATA_USER" "$USER_SCRIPT"
    chmod 755 "$USER_SCRIPT"
    if ! /run/wrappers/bin/sudo -iu "$LIMA_CIDATA_USER" "--preserve-env=$params" "XDG_RUNTIME_DIR=/run/user/$LIMA_CIDATA_UID" "$USER_SCRIPT"; then
      echo "Failed to execute $f (as user $LIMA_CIDATA_USER)"
    fi
    rm "$USER_SCRIPT"
  done
fi

#echo "$LIMA_CIDATA_SLIRP_GATEWAY host.lima.internal" >> /etc/hosts

# write instance ID to boot-done and ssh-ready signal files for Lima (>= 2.1.0)
if [ -n "$LIMA_CIDATA_IID" ]; then
  echo "$LIMA_CIDATA_IID" >/run/lima-ssh-ready
  echo "$LIMA_CIDATA_IID" >/run/lima-boot-done
else
  cp "@CIDATA_MNT@"/meta-data /run/lima-ssh-ready
  cp "@CIDATA_MNT@"/meta-data /run/lima-boot-done
fi

exit 0
